# Generated by Django 2.0.7 on 2019-01-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_book_genre'),
        ('profiles', '0002_auto_20190113_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='follows_genre', to='book.Genre'),
        ),
    ]
