# Generated by Django 2.0.7 on 2019-01-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('types', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
