# Generated by Django 2.0.7 on 2019-01-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(default='History', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='fictional',
            field=models.BooleanField(default=False),
        ),
    ]
