# Generated by Django 2.0.7 on 2019-01-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20190117_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(default='history', max_length=100),
        ),
    ]
