# Generated by Django 2.0.7 on 2019-01-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20190117_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('history', 'HISTORY'), ('drama', 'DRAMA'), ('horror', 'HORROR'), ('thriller', 'THIRLLER')], default='history', max_length=100),
        ),
    ]
