# Generated by Django 2.0.7 on 2019-01-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20190117_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('history', 'HISTORY'), ('drama', 'DRAMA'), ('horror', 'HORROR'), ('thriller', 'THIRLLER'), ('spy', 'SPY'), ('comic', 'COMIC'), ('science', 'SCIENCE')], default='history', max_length=100),
        ),
    ]
