# Generated by Django 2.0.7 on 2019-01-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20190124_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='under_genre', to='book.Genre'),
        ),
    ]
